name: falstore
description: A new Flutter package project.
version: 1.0.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  faltool:
    git:
      url: https://github.com/THE-EXISTING/faltool.git
      ref: V1.0.1

  #PLATFORM: All
  flutter_secure_storage: ^9.2.1
  hive: ^2.2.3

  #PLATFORM: Android, iOS, Linux, MacOS, Windows
  realm: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0

flutter:
